version: '3.8'
 
volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}

  web:
    image: leshkakocheregka/foodgram:latest
    container_name: web
    restart: always
    volumes:
      - static_data:/code/static
      - media_data:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=${secret_key}
      - HOST_IP=${host_ip}
      - DB_NAME=${db_name}
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - EMAIL_HOST=${email_host}
      - EMAIL_PORT=${email_port}
      - EMAIL_HOST_USER=${email_host_user}
      - EMAIL_HOST_PASSWORD=${email_host_password}

  nginx:
    image: nginx:1.19.10
    volumes:
      - static_data:/usr/share/nginx/html/static
      - media_data:/usr/share/nginx/html/media
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - HOST_IP=${host_ip}

