# Generated by Django 3.1.7 on 2021-04-02 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.foodproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default='lunch', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_original_author_name', models.CharField(default='# not defined #', editable=False, max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_for_preparing', models.PositiveSmallIntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=models.SET(recipes.models.get_sentinel_user), related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(through='recipes.Ingredient', to='recipes.FoodProduct')),
                ('tags', models.ManyToManyField(to='recipes.Tag')),
            ],
            options={
                'ordering': ('-pub_date',),
                'unique_together': {('_original_author_name', 'title')},
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'food_product')},
        ),
    ]
