# Generated by Django 3.1.7 on 2021-04-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='purchases',
            field=models.ManyToManyField(related_name='buyers', to='recipes.Recipe'),
        ),
    ]
