# Generated by Django 3.1.7 on 2021-03-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210321_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
