# Generated by Django 3.1.7 on 2021-04-08 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20210409_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Preference',
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
