# Generated by Django 3.2 on 2021-04-24 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Кулинар', 'verbose_name_plural': 'Кулинары'},
        ),
        migrations.AlterField(
            model_name='chef',
            name='favorite_recipes',
            field=models.ManyToManyField(to='recipes.Recipe', verbose_name='Любимые рецепты'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='purchases',
            field=models.ManyToManyField(related_name='buyers', to='recipes.Recipe', verbose_name='Покупки'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='subscriptions',
            field=models.ManyToManyField(through='recipes.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.foodproduct', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(recipes.models.get_sentinel_user), related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Ingredient', to='recipes.FoodProduct', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_for_preparing',
            field=models.PositiveSmallIntegerField(verbose_name='Время приготовления (мин.)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('dinner', 'Обед'), ('supper', 'Ужин')], default='dinner', max_length=9, unique=True, verbose_name='Название'),
        ),
    ]
